
github: [metadata]

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false

# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title

exclude: ["readme.md"]
highlighter: rouge

title: Data 102 Spring 2022
tagline: Data, Inference, and Decisions

baseurl: '/sp22'

sass:
  style: compressed
